-- Crypto Arbitrage Portal — persistent trade model + hourly arbitrage engine
--
-- This file describes the current database architecture used by the portal.
-- It is intended for initial setup on a fresh Supabase project.
-- Existing production databases should be changed through versioned migrations,
-- not by re-running this file wholesale.

create extension if not exists pgcrypto;
create extension if not exists pg_net with schema extensions;

-- ============================================================
-- Persistent trade model
-- ============================================================

create table if not exists public.trades (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  sequence_no bigint generated by default as identity,
  arbitrage_id text not null,
  arbitrage_name text not null,
  anchor_symbol text not null,
  strategy text not null,
  opened_at timestamptz not null,
  initial_anchor_amount numeric(30, 12) not null check (initial_anchor_amount > 0),
  current_asset text not null,
  current_quantity numeric(40, 18) not null check (current_quantity > 0),
  entry_ratio_anchor_per_asset numeric(40, 24) not null check (entry_ratio_anchor_per_asset > 0),
  entry_anchor_amount numeric(30, 12) not null check (entry_anchor_amount > 0),
  closed_at timestamptz,
  closed_anchor_amount numeric(30, 12),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint closed_trade_requires_amount check ((closed_at is null and closed_anchor_amount is null) or (closed_at is not null and closed_anchor_amount is not null and closed_anchor_amount >= 0))
);

create table if not exists public.trade_legs (
  id uuid primary key default gen_random_uuid(),
  trade_id uuid not null references public.trades(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  leg_order integer not null check (leg_order >= 1),
  from_asset text not null,
  to_asset text not null,
  from_amount numeric(40, 18) not null check (from_amount > 0),
  to_amount numeric(40, 18) not null check (to_amount > 0),
  ratio_from_to numeric(40, 24) not null check (ratio_from_to > 0),
  captured_at timestamptz not null,
  created_at timestamptz not null default now(),
  unique (trade_id, leg_order)
);

create table if not exists public.trade_alerts (
  id uuid primary key default gen_random_uuid(),
  trade_id uuid not null references public.trades(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  enabled boolean not null default true,
  rule_type text not null check (rule_type in ('RESULT_PCT_GTE','RESULT_PCT_LTE','ZSCORE_LTE','ZSCORE_GTE')),
  threshold numeric(30, 12) not null,
  channel text not null default 'WHATSAPP' check (channel in ('WHATSAPP','SMS')),
  cooldown_minutes integer not null default 60 check (cooldown_minutes >= 60),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.trade_alert_events (
  id uuid primary key default gen_random_uuid(),
  alert_id uuid not null references public.trade_alerts(id) on delete cascade,
  trade_id uuid not null references public.trades(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  fired_at timestamptz not null default now(),
  anchor_value numeric(30, 12),
  result_pct numeric(30, 12),
  zscore numeric(30, 12),
  channel text not null,
  delivery_status text not null default 'PENDING',
  provider_message_id text,
  error_message text
);

-- ============================================================
-- Common trigger
-- ============================================================

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trades_set_updated_at on public.trades;
create trigger trades_set_updated_at before update on public.trades for each row execute function public.set_updated_at();

drop trigger if exists trade_alerts_set_updated_at on public.trade_alerts;
create trigger trade_alerts_set_updated_at before update on public.trade_alerts for each row execute function public.set_updated_at();

-- ============================================================
-- Hourly arbitrage engine persistence
-- ============================================================

create table if not exists public.hourly_arbitrage_observations (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  arbitrage_id text not null,
  comparative_symbol text not null,
  anchor_symbol text not null,
  evaluated_at timestamptz not null,
  snapshot_at timestamptz,
  ratio numeric,
  avg numeric,
  stdev numeric,
  zscore numeric,
  signal text not null check (signal in ('BUY','HOLD','SELL')),
  gap_pct numeric,
  created_at timestamptz not null default now(),
  unique (user_id, arbitrage_id, comparative_symbol, evaluated_at)
);

create table if not exists public.hourly_arbitrage_state (
  user_id uuid not null references auth.users(id) on delete cascade,
  arbitrage_id text not null,
  comparative_symbol text not null,
  signal text not null default 'HOLD' check (signal in ('BUY','HOLD','SELL')),
  gap_pct numeric,
  zscore numeric,
  gap_threshold_alerted numeric,
  cycle_started_at timestamptz,
  evaluated_at timestamptz not null,
  updated_at timestamptz not null default now(),
  primary key (user_id, arbitrage_id, comparative_symbol)
);

create table if not exists public.hourly_trade_state (
  user_id uuid not null references auth.users(id) on delete cascade,
  trade_id uuid not null references public.trades(id) on delete cascade,
  profit_pct numeric,
  profit_threshold_alerted numeric,
  evaluated_at timestamptz not null,
  updated_at timestamptz not null default now(),
  primary key (user_id, trade_id)
);

-- Official messages produced by the hourly engine. The message text is the
-- single source of truth for all delivery channels. The email_* columns track
-- delivery only; they do not alter the message content.
create table if not exists public.hourly_arbitrage_message_preview (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  evaluated_at timestamptz not null,
  event_type text not null,
  arbitrage_id text,
  comparative_symbol text,
  trade_id uuid references public.trades(id) on delete cascade,
  signal text,
  gap_pct numeric,
  zscore numeric,
  profit_pct numeric,
  threshold numeric,
  message text not null,
  created_at timestamptz not null default now(),
  email_status text not null default 'not_sent' check (email_status in ('not_sent','pending','sent','failed')),
  email_sent_at timestamptz,
  email_provider_id text,
  email_error text,
  unique (user_id, evaluated_at, event_type, arbitrage_id, comparative_symbol, trade_id)
);

create table if not exists public.hourly_arbitrage_scheduler_config (
  id integer primary key check (id = 1),
  cron_secret text not null,
  enabled boolean not null default true,
  dry_run boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_hourly_arbitrage_observations_lookup on public.hourly_arbitrage_observations (user_id, arbitrage_id, comparative_symbol, evaluated_at desc);
create index if not exists idx_hourly_arbitrage_state_user_arb on public.hourly_arbitrage_state (user_id, arbitrage_id);
create index if not exists idx_hourly_trade_state_user on public.hourly_trade_state (user_id);
create index if not exists idx_hourly_arbitrage_message_preview_user_time on public.hourly_arbitrage_message_preview (user_id, evaluated_at desc);
create index if not exists idx_hourly_arbitrage_message_preview_email_retry on public.hourly_arbitrage_message_preview (email_status, evaluated_at) where email_status in ('pending','failed');

-- ============================================================
-- Row-level security
-- ============================================================

alter table public.trades enable row level security;
alter table public.trade_legs enable row level security;
alter table public.trade_alerts enable row level security;
alter table public.trade_alert_events enable row level security;
alter table public.hourly_arbitrage_observations enable row level security;
alter table public.hourly_arbitrage_state enable row level security;
alter table public.hourly_trade_state enable row level security;
alter table public.hourly_arbitrage_message_preview enable row level security;

drop policy if exists trades_select_own on public.trades;
create policy trades_select_own on public.trades for select using ((select auth.uid()) = user_id);
drop policy if exists trades_insert_own on public.trades;
create policy trades_insert_own on public.trades for insert with check ((select auth.uid()) = user_id);
drop policy if exists trades_update_own on public.trades;
create policy trades_update_own on public.trades for update using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists trades_delete_own on public.trades;
create policy trades_delete_own on public.trades for delete using ((select auth.uid()) = user_id);

drop policy if exists trade_legs_select_own on public.trade_legs;
create policy trade_legs_select_own on public.trade_legs for select using ((select auth.uid()) = user_id);
drop policy if exists trade_legs_insert_own on public.trade_legs;
create policy trade_legs_insert_own on public.trade_legs for insert with check ((select auth.uid()) = user_id);
drop policy if exists trade_legs_update_own on public.trade_legs;
create policy trade_legs_update_own on public.trade_legs for update using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists trade_legs_delete_own on public.trade_legs;
create policy trade_legs_delete_own on public.trade_legs for delete using ((select auth.uid()) = user_id);

drop policy if exists trade_alerts_select_own on public.trade_alerts;
create policy trade_alerts_select_own on public.trade_alerts for select using ((select auth.uid()) = user_id);
drop policy if exists trade_alerts_insert_own on public.trade_alerts;
create policy trade_alerts_insert_own on public.trade_alerts for insert with check ((select auth.uid()) = user_id);
drop policy if exists trade_alerts_update_own on public.trade_alerts;
create policy trade_alerts_update_own on public.trade_alerts for update using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists trade_alerts_delete_own on public.trade_alerts;
create policy trade_alerts_delete_own on public.trade_alerts for delete using ((select auth.uid()) = user_id);
drop policy if exists trade_alert_events_select_own on public.trade_alert_events;
create policy trade_alert_events_select_own on public.trade_alert_events for select using ((select auth.uid()) = user_id);
drop policy if exists trade_alert_events_insert_own on public.trade_alert_events;
create policy trade_alert_events_insert_own on public.trade_alert_events for insert with check ((select auth.uid()) = user_id);

drop policy if exists hourly_arbitrage_observations_select_own on public.hourly_arbitrage_observations;
create policy hourly_arbitrage_observations_select_own on public.hourly_arbitrage_observations for select using ((select auth.uid()) = user_id);
drop policy if exists hourly_arbitrage_state_select_own on public.hourly_arbitrage_state;
create policy hourly_arbitrage_state_select_own on public.hourly_arbitrage_state for select using ((select auth.uid()) = user_id);
drop policy if exists hourly_trade_state_select_own on public.hourly_trade_state;
create policy hourly_trade_state_select_own on public.hourly_trade_state for select using ((select auth.uid()) = user_id);
drop policy if exists hourly_arbitrage_message_preview_select_own on public.hourly_arbitrage_message_preview;
create policy hourly_arbitrage_message_preview_select_own on public.hourly_arbitrage_message_preview for select using ((select auth.uid()) = user_id);
drop policy if exists hourly_arbitrage_message_preview_insert_own on public.hourly_arbitrage_message_preview;
create policy hourly_arbitrage_message_preview_insert_own on public.hourly_arbitrage_message_preview for insert with check ((select auth.uid()) = user_id);
drop policy if exists hourly_arbitrage_message_preview_update_own on public.hourly_arbitrage_message_preview;
create policy hourly_arbitrage_message_preview_update_own on public.hourly_arbitrage_message_preview for update using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

revoke all on table public.hourly_arbitrage_scheduler_config from public, anon, authenticated;

-- ============================================================
-- Hourly scheduler RPC
-- ============================================================

create or replace function public.invoke_hourly_arbitrage()
returns void
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  secret_key text;
begin
  select cron_secret into secret_key
  from public.hourly_arbitrage_scheduler_config
  where id = 1 and enabled = true;

  if secret_key is null or secret_key = '' then
    raise exception 'hourly_arbitrage scheduler is disabled or missing secret';
  end if;

  perform net.http_post(
    url := 'https://ckslcyemlwphmilvduzf.supabase.co/functions/v1/hourly-arbitrage-v4',
    headers := jsonb_build_object('Content-Type','application/json','x-cron-secret',secret_key),
    body := jsonb_build_object('dry_run',(select dry_run from public.hourly_arbitrage_scheduler_config where id = 1))
  );
end;
$$;

revoke execute on function public.invoke_hourly_arbitrage() from public, anon, authenticated;

-- The V4 Edge Function source lives under supabase/functions/hourly-arbitrage-v4
-- and is deployed separately from this database schema. Its email delivery
-- uses the RESEND_API_KEY secret and defaults to the Resend onboarding sender
-- until a verified project domain is configured.
