-- Crypto Arbitrage Portal — persistent trade model
-- Run this once in a Supabase SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.trades (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  sequence_no bigint generated by default as identity,
  arbitrage_id text not null,
  arbitrage_name text not null,
  anchor_symbol text not null,
  strategy text not null,
  opened_at timestamptz not null,
  initial_anchor_amount numeric(30, 12) not null check (initial_anchor_amount > 0),
  current_asset text not null,
  current_quantity numeric(40, 18) not null check (current_quantity > 0),
  entry_ratio_anchor_per_asset numeric(40, 24) not null check (entry_ratio_anchor_per_asset > 0),
  entry_anchor_amount numeric(30, 12) not null check (entry_anchor_amount > 0),
  closed_at timestamptz,
  closed_anchor_amount numeric(30, 12),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint closed_trade_requires_amount check (
    (closed_at is null and closed_anchor_amount is null)
    or (closed_at is not null and closed_anchor_amount is not null and closed_anchor_amount >= 0)
  )
);

create table if not exists public.trade_legs (
  id uuid primary key default gen_random_uuid(),
  trade_id uuid not null references public.trades(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  leg_order integer not null check (leg_order >= 1),
  from_asset text not null,
  to_asset text not null,
  from_amount numeric(40, 18) not null check (from_amount > 0),
  to_amount numeric(40, 18) not null check (to_amount > 0),
  ratio_from_to numeric(40, 24) not null check (ratio_from_to > 0),
  captured_at timestamptz not null,
  created_at timestamptz not null default now(),
  unique (trade_id, leg_order)
);

create table if not exists public.trade_alerts (
  id uuid primary key default gen_random_uuid(),
  trade_id uuid not null references public.trades(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  enabled boolean not null default true,
  rule_type text not null check (rule_type in ('RESULT_PCT_GTE','RESULT_PCT_LTE','ZSCORE_LTE','ZSCORE_GTE')),
  threshold numeric(30, 12) not null,
  channel text not null default 'WHATSAPP' check (channel in ('WHATSAPP','SMS')),
  cooldown_minutes integer not null default 60 check (cooldown_minutes >= 60),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.trade_alert_events (
  id uuid primary key default gen_random_uuid(),
  alert_id uuid not null references public.trade_alerts(id) on delete cascade,
  trade_id uuid not null references public.trades(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  fired_at timestamptz not null default now(),
  anchor_value numeric(30, 12),
  result_pct numeric(30, 12),
  zscore numeric(30, 12),
  channel text not null,
  delivery_status text not null default 'PENDING',
  provider_message_id text,
  error_message text
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trades_set_updated_at on public.trades;
create trigger trades_set_updated_at
before update on public.trades
for each row execute function public.set_updated_at();

drop trigger if exists trade_alerts_set_updated_at on public.trade_alerts;
create trigger trade_alerts_set_updated_at
before update on public.trade_alerts
for each row execute function public.set_updated_at();

alter table public.trades enable row level security;
alter table public.trade_legs enable row level security;
alter table public.trade_alerts enable row level security;
alter table public.trade_alert_events enable row level security;

-- Trades: user sees and mutates only their own records.
drop policy if exists trades_select_own on public.trades;
create policy trades_select_own on public.trades for select using (auth.uid() = user_id);

drop policy if exists trades_insert_own on public.trades;
create policy trades_insert_own on public.trades for insert with check (auth.uid() = user_id);

drop policy if exists trades_update_own on public.trades;
create policy trades_update_own on public.trades for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists trades_delete_own on public.trades;
create policy trades_delete_own on public.trades for delete using (auth.uid() = user_id);

-- Legs: access follows the authenticated owner on both the leg and parent trade.
drop policy if exists trade_legs_select_own on public.trade_legs;
create policy trade_legs_select_own on public.trade_legs
for select using (auth.uid() = user_id);

drop policy if exists trade_legs_insert_own on public.trade_legs;
create policy trade_legs_insert_own on public.trade_legs
for insert with check (auth.uid() = user_id);

drop policy if exists trade_legs_update_own on public.trade_legs;
create policy trade_legs_update_own on public.trade_legs
for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists trade_legs_delete_own on public.trade_legs;
create policy trade_legs_delete_own on public.trade_legs
for delete using (auth.uid() = user_id);

-- Alerts/events follow the authenticated owner.
drop policy if exists trade_alerts_select_own on public.trade_alerts;
create policy trade_alerts_select_own on public.trade_alerts for select using (auth.uid() = user_id);

drop policy if exists trade_alerts_insert_own on public.trade_alerts;
create policy trade_alerts_insert_own on public.trade_alerts for insert with check (auth.uid() = user_id);

drop policy if exists trade_alerts_update_own on public.trade_alerts;
create policy trade_alerts_update_own on public.trade_alerts for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists trade_alerts_delete_own on public.trade_alerts;
create policy trade_alerts_delete_own on public.trade_alerts for delete using (auth.uid() = user_id);

drop policy if exists trade_alert_events_select_own on public.trade_alert_events;
create policy trade_alert_events_select_own on public.trade_alert_events for select using (auth.uid() = user_id);

drop policy if exists trade_alert_events_insert_own on public.trade_alert_events;
create policy trade_alert_events_insert_own on public.trade_alert_events for insert with check (auth.uid() = user_id);
